controllers/ManegerController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\maneger\AddForm;
use app\models\maneger\Team;
use app\models\maneger\Players;
use app\models\maneger\AddPlayersForm;

class ManegerController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionShowTeam(){
        
       if ($id = Yii::$app->request->get('id')){
           
          Players::deleteAll(['team_id' => $id]);
           
           $team = Team::find()->where(['id' => $id])->one();
           $team->delete();
    
       }
       
      
       $team = Team::find()->asArray()->all();
        
        return $this->render('show_team', compact('team'));
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionAddTeam(){
        
        $urlButton = 'index.php?r=maneger/add-team';
        $button = 'Додати';
        $model = new AddForm();
        $edit_data_team = 'Додати команду';
       
     
        if($model->load(Yii::$app->request->post()) && $model->save()){
            
            return $this->redirect('index.php?r=maneger/show-team');
           
        }
        
        return $this->render('add_team', compact('model','urlButton','button','edit_data_team'));
       
    }

   
    public function actionShowPlayers(){
        
        if($id = Yii::$app->request->get('id')){
            
         // Players::deleteAll(['team_id' => $id]);
           
          $players = Players::find()->where(['id' => $id])->one();
          $players->delete();   
        }
        
        $team_id = Yii::$app->request->get('team_id');
        $players = Players::findAll(['team_id'=>$team_id]);
        return $this->render('show_players', compact('players','team_id'));
    }
    
    
    public function actionEditTeam(){
        
        $model = new AddForm();
        $button = 'Змінити';
        $urlButton = 'index.php?r=maneger/edit-team&id='.Yii::$app->request->get('id');
        $edit_data_team = 'Змінити дані команди';
        if(Yii::$app->request->post()){
            
            $teamAR = AddForm::find()->where(['id' =>Yii::$app->request->get('id')])->one();
            $teamAR->load(Yii::$app->request->post());
            $teamAR->save();
            return $this->redirect('index.php?r=maneger/show-players');
           
        }
        
     
        return $this->render('add_team',compact('button','model','urlButton','edit_data_team'));
    }

    
    public function actionAddPlayers(){
        $model = new AddPlayersForm();
        $button = 'Додати';
        $team_id = Yii::$app->request->get('team_id');
        $urlButton = '/index.php?r=maneger/add-players&team_id='.$team_id;
        $edit_players = 'Додати гравця';
        if($model->load(Yii::$app->request->post())){
            $model->team_id = $team_id;
            $model->save();
            return $this->redirect('index.php?r=maneger/show-players&team_id='.$team_id);
           
        }
        
        return $this->render('add_players', compact('model','urlButton','button','edit_players'));
        
    }
    
    public function actionEditPlayers(){
        
        $model = new AddPlayersForm();
        $button = 'Змінити';
        $urlButton = 'index.php?r=maneger/edit-players&team_id='.Yii::$app->request->get('team_id');
        $urlButton .= '&edit_id='.Yii::$app->request->get('edit_id'); 
        $edit_players = 'Змінити дані гравця';
        if(Yii::$app->request->post()){
            
            $playersAR = AddPlayersForm::find()->where(['id' =>Yii::$app->request->get('edit_id')])->one();
            $playersAR->load(Yii::$app->request->post());
            $playersAR->team_id = Yii::$app->request->get('team_id');
            $playersAR->save();
        
            return $this->redirect('index.php?r=maneger/show-players&team_id='.Yii::$app->request->get('team_id'));
           
        }
        
     
        return $this->render('add_players',compact('button','model','urlButton','edit_players'));
        
        
    }
}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Головна', 'url' => ['/maneger/index']],
            ['label' => 'Список команд', 'url' => ['/maneger/show-team']],
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/maneger/add_players.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = $edit_players;
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    

    <?php $form = ActiveForm::begin([
        'action' => $urlButton,
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'firstname')->textInput(['autofocus' => true])->label('І\'мя') ?>
        <?= $form->field($model, 'secondname')->textInput()->label('Прізвище') ?>
        <?= $form->field($model, 'birthday')->textInput(['placeholder' => 'YYYY-MM-DD \'Наприклад 1990-10-10\''])->label('День народження') ?>
        <?= $form->field($model, 'position')->textInput()->label('Позиція на полі') ?>
        <?= $form->field($model, 'team_id')->hiddenInput(['value'=> Yii::$app->request->get('team_id')])->label(false) ?>
       
    
       

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton($button, ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

   
</div>

views/maneger/add_team.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = $edit_data_team;
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    

    <?php $form = ActiveForm::begin([
        'action' => $urlButton,
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'name')->textInput(['autofocus' => true])->label('І\'мя') ?>

        <?= $form->field($model, 'foundation')->textInput(['placeholder' => 'YYYY-MM-DD \'Наприклад 1990-10-10\''])->label('Дата заснування') ?>
    
       

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton($button, ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

   
</div>

views/maneger/index.php
<?php

use yii\helpers\Html;

$this->title = 'Futboll Manager';
?>
<div style="text-align: center " class="site-index">

    <H1 style="text-align: center">Football Manager</H1>
    <?php echo Html::a('Список команд', ['maneger/show-team'], ['class' => 'button']) ?>
    
</div>

views/maneger/show_players.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;


?>
<div class="table">
    <h1><?= Html::encode($this->title) ?></h1>
    <?php echo Html::a('Додати гравця', ['maneger/add-players', 'team_id' => $team_id], ['class' => 'button']) ?>

    <table border="1">
        <tr>
            <th>id</th>
            <th>id команди</th>
            <th>Ім'я гравця</th>
            <th>Прізвище гравця</th>
            <th>День народження</th>
            <th>Позиція на полі</th>
            <th>Керування</th>
                
        </tr>
        <?php 
        
        foreach ($players as $value){
           echo "<tr  style = 'cursor: pointer;'>";
           foreach ($value as $val){
               echo "<th>";
               echo "$val";
               echo "</th>";
           }
           
           
           echo "<th>";
           echo Html::a('Редагувати ', ['maneger/edit-players','edit_id' =>$value['id'],'team_id'=>$team_id, ['class' => 'profile-link']]);
           echo Html::a('Видалити', ['maneger/show-players','team_id'=>$team_id,'id' => $value['id']], ['class' => 'profile-link']);
           echo "</th>";
           
            
            echo "</tr>";
        }
        
        ?>
    </table>
    
</div>

views/maneger/show_team.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;


?>
<div class="table">
    <h1><?= Html::encode($this->title) ?></h1>
    
    <?php echo Html::a('Додати команду', ['maneger/add-team'], ['class' => 'button']) ?>

    <table border="1">
        <tr>
            <th>id</th>
            <th>Ім'я команди</th>
            <th>Дата заснування</th>
            <th>Керування</th>
                
        </tr>
        <?php 
        
        foreach ($team as $value){
           echo "<tr  style = 'cursor: pointer;' onclick=\"document.location = './index.php?r=maneger/show-players&team_id=$value[id]';\">";
           foreach ($value as $val){
               echo "<th>";
               echo "$val";
               echo "</th>";
           }
           echo "<th>";
           echo Html::a('Редагувати ', ['maneger/edit-team','id' => $value['id']], ['class' => 'profile-link']);
           echo Html::a('Видалити', ['maneger/show-team','id' => $value['id']], ['class' => 'profile-link']);
           echo "</th>";
            
            echo "</tr>";
        }
        
        ?>
    </table>
    
</div>